### ISSUE TITLE
vg_lite_tvg example

### ISSUE THREAD

**Issue by espressif2022** [FASTSHIFT/vg_lite_tvg#3]
我尝试在 `lvgl v9` 上运行 `vg_lite_tvg demo`，是否可以这里的 main 函数代码参考一下？

**Comment by FASTSHIFT** [comment]
LVGL v9 内部已集成 [VG-Lite 模拟器](https://github.com/lvgl/lvgl/tree/master/src/others/vg_lite_tvg)，打开配置即可：

```menuconfig
LV_USE_DRAW_VG_LITE=y       # 打开VG-Lite渲染后端
LV_VG_LITE_USE_GPU_INIT=y   # 打开gpu_init初始化调用
LV_VG_LITE_USE_ASSERT=y     # 打开GPU传参检查
LV_USE_THORVG=y
LV_USE_THORVG_INTERNAL=y    # 打开ThorVG
LV_USE_VG_LITE_THORVG=y     # VG-Lite模拟器
```

**Comment by espressif2022** [comment]
> LVGL v9 内部已集成 [VG-Lite 模拟器](https://github.com/lvgl/lvgl/tree/master/src/others/vg_lite_tvg)，打开配置即可：
> 
> ```
> LV_USE_DRAW_VG_LITE=y       # 打开VG-Lite渲染后端
> LV_VG_LITE_USE_GPU_INIT=y   # 打开gpu_init初始化调用
> LV_VG_LITE_USE_ASSERT=y     # 打开GPU传参检查
> LV_USE_THORVG=y
> LV_USE_THORVG_INTERNAL=y    # 打开ThorVG
> LV_USE_VG_LITE_THORVG=y     # VG-Lite模拟器
> ```

好的，谢谢
