### ISSUE TITLE
add vg_lite_get_transform_matrix function

### ISSUE THREAD

**Issue by xiaoyu-ebox** [FASTSHIFT/vg_lite_tvg#4]
Hi, Can you add an implementation of vg_lite_get_grad_matrix function? thank you.

vg_lite_matrix_t* vg_lite_get_grad_matrix(vg_lite_linear_gradient_t *grad);

**Comment by FASTSHIFT** [comment]
> Hi, Can you add an implementation of vg_lite_get_grad_matrix function? thank you.
> 
> vg_lite_matrix_t* vg_lite_get_grad_matrix(vg_lite_linear_gradient_t *grad);

It's here: https://github.com/FASTSHIFT/vg_lite_tvg/blob/main/vg_lite_tvg.cpp#L1685

**Comment by xiaoyu-ebox** [comment]
> > Hi, Can you add an implementation of vg_lite_get_grad_matrix function? thank you.
> > vg_lite_matrix_t* vg_lite_get_grad_matrix(vg_lite_linear_gradient_t *grad);
> 
> It's here: https://github.com/FASTSHIFT/vg_lite_tvg/blob/main/vg_lite_tvg.cpp#L1685

Thank you for your reply. Sorry, I copied it wrong. It should be this function.：

/* Generate a 3x3 homogenous matrix to transform 4 source coordinates to 4 target coordinates. */
vg_lite_error_t vg_lite_get_transform_matrix(vg_lite_point4_t src, vg_lite_point4_t dst, vg_lite_matrix_t *mat);

**Comment by FASTSHIFT** [comment]
> vg_lite_get_transform_matrix

You can copy the source code of the VG-Lite driver and send a PR to add it.

**Comment by xiaoyu-ebox** [comment]
> > vg_lite_get_transform_matrix
> 
> You can copy the source code of the VG-Lite driver and send a PR to add it.

vg-lite driver only function declaration, implementation in the library.

**Comment by FASTSHIFT** [comment]
You can easily search for the full source code on github:
![1720239223818](https://github.com/FASTSHIFT/vg_lite_tvg/assets/26767803/21d705a7-2c72-4aac-a09c-b6f461059dfe)

**Comment by xiaoyu-ebox** [comment]
Oh oh oh thank you very much, I forgot that github search code is better than Google, I didn't find it in Google, thank you.
